# Generated by Django 5.2.13 on 2026-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_restauran_restaurantypes_restauranphotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(choices=[('seller', 'Продавец'), ('primeSeller', 'Главный продавец'), ('sales_manager', 'Керівник відділу продажів')], default='seller', max_length=20),
        ),
        migrations.AddField(
            model_name='sellinfo',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='start_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellinfo',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
